study_id    = "ENSEMBLE"
data_dir    = "./SDTM_Data_Set"
sdtmig      = "./SDTM_Master/SDTMIG_v3.4.xlsx"
terminology = "./SDTM_Master/SDTM Terminology.xlsx"
mapping     = "./SDTM_Data_Set/ENSEMBLE_OperationConf.xlsx"
output      = "./output"
